### PR TITLE
Fix "Invalid PlantUML generated" #221

### PR DESCRIPTION
**Pull request by drazzib**
Use `asUrlToDirectory` as target link for components

Fix for #221

### CODE REVIEW

**Comment by jp7677** [comment]
Thanks a lot for your PR. Looks good!
Could you please also add a test in https://github.com/avisi-cloud/structurizr-site-generatr/blob/main/src/test/kotlin/nl/avisi/structurizr/site/generatr/site/C4PlantUmlExporterWithElementLinksTest.kt that validates the correct behavior?

**Comment by drazzib** [comment]
Hi @jp7677 

I've just fixed the test :)

**Comment by jp7677** [comment]
> Hi @jp7677
> 
> I've just fixed the test :)

Thanks! I don't think this is the scenario you run into, the link looks now better but it wasn't empty. Could you still try to catch your scenario in a test?

**Review by jp7677 — CHANGES_REQUESTED** [review]
See above comment

**Comment by jp7677** [comment]
@drazzib I've manually pulled your commits into another branch added another commit that prevents those links  altogether. See https://github.com/avisi-cloud/structurizr-site-generatr/pull/223

**Comment by drazzib** [comment]
> @drazzib I've manually pulled your commits into another branch added another commit that prevents those links altogether. See #223

Perfect 👍🏻 
NB : I haven't had time to read your comment in the last two days, sorry.

**Comment by jp7677** [comment]
> > @drazzib I've manually pulled your commits into another branch added another commit that prevents those links altogether. See #223
> 
> Perfect 👍🏻 NB : I haven't had time to read your comment in the last two days, sorry.

No worries. Would be cool though if you could confirm that your issue is completely resolved on master.

**Pull request closed without merging**
