### PR TITLE
Add the ability to zoom in and pan around the SVG diagram.

### PR DESCRIPTION
**Pull request by qtzar**
Added the ability to zoom in on a part of a diagram.

- Double click a non-clickable area of the diagram to zoom it in.
- Hold the control key and use the mouse wheel/scroll to zoom in/out
- Click and hold a zoomed in diagram and move mouse to pan
- Pinch on trackpad/mobile to zoom in and out

Still to do : Add button(s) to control zoom under the sag, add button to reset to original size, add some sort of bounding box so that the zoomed element doesn't take over the full screen.

### CODE REVIEW

**Comment by qtzar** [comment]
@dirkgroot Would love to get your input on this early stage concept.

**Comment by qtzar** [comment]
Found a better SVG Zooming library that gives me the ability to zoom within the svg's container and add control buttons but lost the ability to require the control key to be held down to zoom with mouse.

**Comment by qtzar** [comment]
Still working on this functionality. I moved the Pan/Zoom version of the SVG to a modal. I was unhappy with how having it directly on the page was interfering with normal site usage as you couldn't;t scroll up/down the page when the mouse was over the svg area.

I still need to figure out a good style for the 'zoom' button that surfaces the modal.

For the modal itself I used the built in Bulma CSS's modal and their sample JS so that additional resources would not have to be added to the site. I also added a new property to the DSL to allow users to enable/disable this functionality. When disabled (default) the JS for the modal and pan/zoom are excluded from the generated html.

@dirkgroot @jp7677 Any feedback?

**Comment by qtzar** [comment]
This is what I ended up with for the positioning of the 'zoom/pan' button. I split the FigCaption in to two lines, one for the title and one for the download links and added the zoom button as a link there.

Screenshot 2023-10-11 at 3 59 28 PM

**Comment by qtzar** [comment]
here is what I did for the positioning of the 'zoom/pan' button that opens the modal window. I split the caption on the diagram in to two lines, first for the diagram title and the second for the download links. When the Zoom feature is enabled the extra link is added to the list.

Screenshot 2023-10-11 at 3 59 28 PM

**Comment by jp7677** [comment]
Hi @qtzar sorry again for the late response, I promise, this one is next on my list. 
Already a heads up, could you please organize new browser dependencies according to https://github.com/avisi-cloud/structurizr-site-generatr/pull/328 ?

**Comment by qtzar** [comment]
@jp7677 Much appreciated & I have setup the browser dependency as requested.

**Comment by jp7677** [comment]
@qtzar Please see https://github.com/avisi-cloud/structurizr-site-generatr/pull/334

**Pull request closed without merging**
