### PR TITLE
Add favicon and logo documentation

### PR DESCRIPTION
**Pull request by Zaijo**
Add documentation for #135

### CODE REVIEW

**Comment by Zaijo** [comment]
@jp7677 can you please correct the documentation so it documents real steps?

**Comment by Zaijo** [comment]
It's ready from my side. Working for me as documented.

**Comment by jp7677** [comment]
Thanks a lot for taking the initiative. Would you mind expanding the documentation to include all the branding properties? I think it is also a good idea to start with an introduction and a table showing the separate properties and its meanings.

**Comment by Zaijo** [comment]
I'm not aware of any other options. Do you have some link with details? On the other hand, this is quite the maximum I'm able to offer these days.

**Comment by jp7677** [comment]
The other two options are the primary and secondary colors, see https://github.com/avisi-cloud/structurizr-site-generatr/blob/main/docs/example/workspace.dsl#L159

**Comment by jp7677** [comment]
Superseded by https://github.com/avisi-cloud/structurizr-site-generatr/pull/206

**Pull request closed without merging**
