### PR TITLE
Add support for setting a favicon

### PR DESCRIPTION
**Pull request by jp7677**
Just do it simple and copy a `favicon,ico ` (when exists) from the root assets directory to the root export directory.
Note that in case of multiple branches, the last favicon wins. 

Let me know what you think, since it is kind-of implicit magic :), we might also do this more explicitly by adding another structurizr property to the view properties (similar like the colors but with e.g. a relative path to the favicon in the assets directory)

### CODE REVIEW

**Comment by jp7677** [comment]
Note also that this doesn't obviously works when the site is hosted within a virtual directory, but I guess people should know when working with such a scenario.

**Comment by jp7677** [comment]
This introduces two new view properties:
- `structurizr.style.favicon.path` - a path to a favicon.ico relative to the assets directory (e.g. `favicon.ico` when located in the assets directory )
- `structurizr.style.favicon.branch` - a branch name, e.g. `main`, when the favicon should only be copied from a specific branch. This should be used when generating from a git repository to avoid copying (and overriding) the favicon multiple times from different branches.

**Comment by dirkgroot** [comment]
This solution makes it hard to reason about which branch will eventually "provide" the favicon. This is due to the fact that the favicon is placed in the root directory of the site. This is actualy discouraged by W3C. See [W3C's How to Add a Favicon to your Site](https://www.w3.org/2005/10/howto-favicon) page for more information.

Also, this "implicit" method doesn't work if you're not hosting the generated site at the root of a domain (for example: https://docs.mycoolsystem.com/architecture).

I think that a better solution would be to use the preferred method of putting a `<link rel="icon"... />` element in the `head` element of every generated page.

**Comment by dirkgroot** [comment]
Looks neat, and works like a charm, thanks!

**Comment by Zaijo** [comment]
@jp7677 thanks for the PR, but how to enable favicon in my project? Could you please add a short docs in e.g. README or somewhere? I tried adding to root, adding to generated site manually ... version 1.0.25

Is the property `structurizr.style.favicon.path` required, or does it pick up automagically?

**Comment by jp7677** [comment]
@Zaijo yes, you have to set the property explicitly. See the example for how to use it.

Yeah, I fully agree on the readme.

**Comment by Zaijo** [comment]
What do you mean "the example"? I have't found any favicon file in the repo.Where should I place it? What is the property folder based? In current directory `pwd` where I run `structurizr-site-generatr`?

**Comment by jp7677** [comment]
See https://github.com/avisi-cloud/structurizr-site-generatr/tree/main/docs/example where you'll the favicon here https://github.com/avisi-cloud/structurizr-site-generatr/tree/main/docs/example/assets/site and the corresponding setting here https://github.com/avisi-cloud/structurizr-site-generatr/blob/main/docs/example/workspace.dsl#L161 
The path is relative to the root asset path.

**Pull request merged**
